// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/player-signup-modal/Current.tsx": () => import("../components/mockups/player-signup-modal/Current.tsx"),
  "./components/mockups/player-signup-modal/Integrated.tsx": () => import("../components/mockups/player-signup-modal/Integrated.tsx")
};
