// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/action-modal/Current.tsx": () => import("../components/mockups/action-modal/Current.tsx"),
  "./components/mockups/action-modal/Immersive.tsx": () => import("../components/mockups/action-modal/Immersive.tsx")
};
